[0.000000] (-) TimerEvent: {}
[0.001231] (-) JobUnselected: {'identifier': 'auto_nav'}
[0.001606] (lidar-sole-servo_test) JobQueued: {'identifier': 'lidar-sole-servo_test', 'dependencies': OrderedDict()}
[0.002438] (lidar-sole-servo_test) JobStarted: {'identifier': 'lidar-sole-servo_test'}
[0.099214] (-) TimerEvent: {}
[0.200051] (-) TimerEvent: {}
[0.300713] (-) TimerEvent: {}
[0.401369] (-) TimerEvent: {}
[0.501997] (-) TimerEvent: {}
[0.602608] (-) TimerEvent: {}
[0.703231] (-) TimerEvent: {}
[0.803948] (-) TimerEvent: {}
[0.904721] (-) TimerEvent: {}
[1.005432] (-) TimerEvent: {}
[1.106437] (-) TimerEvent: {}
[1.207109] (-) TimerEvent: {}
[1.307738] (-) TimerEvent: {}
[1.408464] (-) TimerEvent: {}
[1.438307] (lidar-sole-servo_test) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_identification/ros.py", line 129, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 281, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.8/subprocess.py", line 516, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', "import sys;from setuptools.extern.packaging.specifiers import SpecifierSet;from distutils.core import run_setup;dist = run_setup(    \'setup.py\', script_args=(\'--dry-run\',), stop_after=\'config\');skip_keys = (\'cmdclass\', \'distclass\', \'ext_modules\', \'metadata\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\'_\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\'metadata\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\'license_files\', \'provides_extras\')};sys.stdout.buffer.write(repr(data).encode(\'utf-8\'))"]\' returned non-zero exit status 1.\n'}
[1.440173] (lidar-sole-servo_test) JobEnded: {'identifier': 'lidar-sole-servo_test', 'rc': 1}
[1.450522] (-) EventReactorShutdown: {}
